[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "openai-whisper>=20240930",
    "pytube>=15.0.0",
    "yt-dlp>=2025.6.9",
]
